### ISSUE TITLE
The Travis CI badge is not working

### ISSUE THREAD

**Issue by artemrizhov** [niccokunzmann/hanging_threads#20]
It says the build is faling. But if I click the badge then I see a [page](https://travis-ci.org/niccokunzmann/hanging_threads) that is saying "This is not an active repository"

**Comment by artemrizhov** [comment]
@niccokunzmann I'm not sure what is the problem. You probably should know what is going wrong.

**Comment by artemrizhov** [comment]
Oh, there are more texts below :)

> You don't have sufficient rights to enable this repo on Travis. 
> Please contact the admin to enable it or to receive admin rights yourself.

**Comment by niccokunzmann** [comment]
Seems like collaborators do not have admin rights.

**Comment by niccokunzmann** [comment]
I think, I resolved the issue. Please check and close.

**Comment by artemrizhov** [comment]
It works now!
