### ISSUE TITLE
Stop reccurring messages for hanging threads

### ISSUE THREAD

**Issue by artemrizhov** [niccokunzmann/hanging_threads#21]
If a thread hangs, this incedente should be reported once only. If the hanging thread awakes, then this event should be logged too. No repeating messages should be logged in the interval between these two events.
This behaviour is proposed to solve the problem of swamping messages discussed in #15.

**Comment by artemrizhov** [comment]
@niccokunzmann I propose to freeze the current set of features in branch `1.x` and make the master branch containing the newest features. It also may be a good idea to move the base work to branch `develop` to make the `master` branch containing latest working version of the lib.

**Comment by niccokunzmann** [comment]
Sure, please go ahead.
