### ISSUE TITLE
Deploy Process

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/hanging_threads#26]
How would we like deploying to work?

I could image:

1. We create a tag and it pushes the release #7 
2. Every commit in the master branch pushes the package with an increasing version number to pypi.

(1) is already implemented [here](https://github.com/fossasia/knittingpattern/blob/master/.travis.yml) but requires extra effort
(2) allows just a new upload by merging and is very convenient. It allows us to deploy a feature very fast. This may be additionally nice for people who would like to see a bug fixed and have a version with this.

What are your ideas?

**Summary**

- [x] upload on tag: #7 
  - The tag is named as the version: NUMBER.NUMBER.NUMBER
  - The version is uploaded to pypi
- [x] create tags on version branches:
  - version branches are named NUMBER.NUMBER
  - every commit on a version branch is creates 
     - a commit with the `__version__` variable changed
     - a tag for the commit with the changes `__version__` variable
  - pushes the tag

**Comment by artemrizhov** [comment]
In case of (2) there probably should be a process that increases the version number and does the commit with this version. And we will have a lot of such commits in the git log. I think it's better to use tags. It should not be too hard to create new tag, but you will have ability to control the deployment process.

**Comment by artemrizhov** [comment]
Actually second method may work too since we've moved work to the develop branch in #30. I'm just not sure how would you control minor/major version change.

**Comment by niccokunzmann** [comment]
Proposal:

- We work on some branch e.g.  `fix-bug-xy` [Responsibility: Developer]
- There is a branch for releases of a certain version e.g. `2.1` [Responsibility: Developer]
- Every commit in the `2.1` branch gets a tag with increasing version number: `2.1.1`, `2.1.2`, `2.1.3`, ... [Responsibility: Travis]
- Every tag has the string behind the `__version__ = "..."` with the actual version number. [Responsibility: Travis]

What are your thoughts?

**Comment by artemrizhov** [comment]
Sounds well. This probably should work.

**Comment by artemrizhov** [comment]
What about `master` vs `develop`? What workflow for these branches do you assume?

**Comment by niccokunzmann** [comment]
They could be deleted I have no purpose for them. I do not know. Maybe, we need develop. Master would be the version we work on.

What I like about this is: if we get a pull-request, we can merge it and within minutes the person can pip install the latest version from pypi. That should be totally encouraging to contribute.

**Comment by artemrizhov** [comment]
I think at least master should remain, so that anybody can checkout latest stable version. Also I think that any changes should be tested before they are pushed to master or version branch. This is why develop is used usually.

**Comment by artemrizhov** [comment]
By the way, it is possible to pip install directly from public git repo.

**Comment by niccokunzmann** [comment]
@artemrizhov I added a summary. Can you check?

In the settings, we can change the branch but it is not recommended. So, it should stay the same.

![image](https://cloud.githubusercontent.com/assets/564768/22177001/0df3a192-e016-11e6-9387-53060d0f06f1.png)

Maybe we merge master into the latest version branch from time to time - they are the 'deploy' or 'production' branches. If you like to have a develop branch, we try it out.

Process would be: pull-request →  master →  2.1 branch →  tag → upload to pypi

Either way "upload on tag" can be implemented.

What do you think?

**Comment by artemrizhov** [comment]
Well, the overall idea looks good. Are you going to add support of automatic "→ tag → upload to pypi"?

It seems the develop branch is excess for this project, so working on master probably would be fine.

**Comment by niccokunzmann** [comment]
@artemrizhov #34 is the part tag → upload to pypi the other point comes in an other PR.
You can merge.

**Comment by niccokunzmann** [comment]
I am working on branch v0.0 to test it.

TODO:
- [x] check that the `__version__` does not start with 'v'
- [x] make it work on travis who has different variables and checks out commits and not branches.

**Comment by niccokunzmann** [comment]
So, the deployment process is done. I will create a pull-request with additional infomration.
