### ISSUE TITLE
Document what the functions do

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/hanging_threads#27]
We have some functions there. In order for other people to use them they should have some documentation.

- [x] functions in the module
- [ ] StoppableThread
  - [ ] short description first line, long description 3rd line, ++
  - [ ] stop function
  - [ ] is_stopped

**Comment by MarkoMackic** [comment]
How would you document them ? in separate doc file, or directly in code ?

**Comment by niccokunzmann** [comment]
I would use strings directly in the code.

**Comment by niccokunzmann** [comment]
@MarkoMackic #29 Please reference the issues, so we see updates here, too.

**Comment by niccokunzmann** [comment]
Thanks for your code. It looks much better.

**Comment by MarkoMackic** [comment]
This can be closed I think.
