### ISSUE TITLE
add __all__ variable

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/hanging_threads#28]
There should be a variable named `__all__` which contains only the functions which are useful.
This is needed when doing `from hanging_threads import *` - then, you would only like to import these functions.

- add `__all__` variable
- decide which functions are most important and which should be hidden.

**Comment by artemrizhov** [comment]
It seems that only `start_monitoring()` is really needed in most cases, so I'm not sure if `from hanging_threads import *` makes any sence. It's better to use explicit import for single function: `from hanging_threads import start_monitoring`. Can you imagine a use case for `import *`?

**Comment by MarkoMackic** [comment]
My opinion is  that `__all__` isn't needed currently.
