### ISSUE TITLE
Fix supported Python versions

### ISSUE THREAD

**Issue by artemrizhov** [niccokunzmann/hanging_threads#32]
Travis CI is configured to check hanging_threads against Python 2.6-3.6. However setup.py claims it also supports 2.3 and 2.4. What versions are really should be supported?

If you ask me then I'd propose to drop support of any version below 2.6 because of incompatibilities in the threading module. I'm just not sure it makes sense to support such compatibility.

**Comment by niccokunzmann** [comment]
I think, 2.3 and 2.4 and 2.5 can be dropped until someone likes to take this on.
2.7 is still supported. 2.6 was added because of https://gist.github.com/niccokunzmann/6038331#gistcomment-1901386

**Comment by artemrizhov** [comment]
This should be fixed in v1.1 and then merged to master.
