### ISSUE TITLE
Replace tests_per_second with test_interval

### ISSUE THREAD

**Issue by artemrizhov** [niccokunzmann/hanging_threads#33]
Every time I'm looking on this option I do convertation from interval to frequency and vise versa. I think this is probably because intervals are widely used in programming. Also I have to pass fractional values when I want the check to happen once per two seconds or more.

For this specific task I think interval is more convenient because it is easy to compare interval with hanging time, while it's hard to compare frequency with time without doing convertation.

**Comment by artemrizhov** [comment]
@niccokunzmann What is your opinion about this?

**Comment by niccokunzmann** [comment]
Sure, let's do this. I think it is important to document the unit: seconds or milliseconds.

**Comment by MarkoMackic** [comment]
I think it's generally better to use milliseconds as unit or should we support unit to be changed ?  I'll reference this now

**Comment by niccokunzmann** [comment]
All is fine. I think, we can close this. If I forgot something, please re-open!
