### ISSUE TITLE
Choose limit for line length and reformat the code

### ISSUE THREAD

**Issue by artemrizhov** [niccokunzmann/hanging_threads#48]
PEP8 [recommends](https://www.python.org/dev/peps/pep-0008/#maximum-line-length) to limit all lines to a maximum of 79 characters. While I was trying to follow PEP8, new commits break this rule:

- https://github.com/niccokunzmann/hanging_threads/blob/daa569e2f6ec06f98ae2d452d77de0f958a5f0d4/hanging_threads.py#L8
- https://github.com/niccokunzmann/hanging_threads/blob/daa569e2f6ec06f98ae2d452d77de0f958a5f0d4/hanging_threads.py#L44-L45

We need to choose the line length limit for this project for the code style unification.

**Comment by artemrizhov** [comment]
@niccokunzmann What are your thoughts?

**Comment by artemrizhov** [comment]
PEP 8 about comments:

> For flowing long blocks of text with fewer structural restrictions (docstrings or comments), the line length should be limited to 72 characters.

**Comment by niccokunzmann** [comment]
We can create a pep8 check, use pep8 or flakes and make travis run tests so we see when pep8 is violated. This also generates easy-to-solve issues for new contributors. There is also landscape - a service showing code quality. If we connect landscape, we have a nice UI for the style errors.

**Comment by MarkoMackic** [comment]
Resolving current PEP8 line lenght problems.

**Comment by artemrizhov** [comment]
@MarkoMackic Is there any reason you add blank line before closing `"""`?

**Comment by artemrizhov** [comment]
So we desided to follow PEP 8 recommendations about the line leghts.
I think this issue may be closed. I'll create new issue for automated pep8 check.
