### ISSUE TITLE
Where to serve docs?

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/hanging_threads#60]
Docs can be

- uploaded to pypi
- served by readthedocs
- in the docs folder and that's enough #59 
- serve the docs as a jekyll site

Any thoughts? We can use the first-implemented makes it approach.

**Comment by artemrizhov** [comment]
I think the simplest method is the best one for this small library. There is no so many information to create multipage documentation. So the docs folder and the README file is the best choice.

**Comment by niccokunzmann** [comment]
#59 is the way to go, then.
