### ISSUE TITLE
Make 2.x and 1.x be deploy branches

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/hanging_threads#61]
#26 introduces #56 - the deployment functionality for branches.

Let's rename them the branches:

- [x] 2.x -> 2.0
  - [x] merge master into 2.0
- [x] 1.x -> 1.1
  - [x] cherry-pick #56 into 1.1
- [x] merge 1.1 into master

What are your thoughts? @artemrizhov

**Comment by artemrizhov** [comment]
No problems. I'd just avoid cherry-picking because this will produce conflicts. You will not be able to merge same changes to both branches.

If you want to add some feature both to 1.x and 2.x then it's better to start the branch from 1.x and then merge both into 1.x and 2.x, or merge into 1.x then merge 1.x into 2.x if there is no conflicts yet.

Since you have already merged #56 into master, it can not be just rebased onto 1.x. We have to hard reset the master branch to the previous commit before fixing. This will require forced push to the master branch, which is denied usually. It probably can be allowed via the repository settings page.

**Comment by niccokunzmann** [comment]
I removed the protection of the master branch. You can do this.
Other idea:

If we add the pick to 1.1 #61 and I remove the merge conflicts for merging 1.1 into master, would this also work for future changes?

**Comment by artemrizhov** [comment]
I don't have rights to push into your repo. You can do this by executing following commands:
$ git checkout master
$ git reset --hard bca4679
$ git push origin --force

**Comment by artemrizhov** [comment]
> If we add the pick to 1.1 #61 and I remove the merge conflicts for merging 1.1 into master, would this also work?

I'd avoid such tricks because I don't know git on such low level, but I've got a lot of problems with history when doing strange things before. :)

**Comment by niccokunzmann** [comment]
did the force reset

**Comment by artemrizhov** [comment]
Ok. I'm rebasing the branch onto 1.x now.

**Comment by niccokunzmann** [comment]
have a look at #62 Would it be the next step to merge this?

**Comment by artemrizhov** [comment]
Oh, you cherry picked it already. So we can merge it anywhere now. :)

**Comment by niccokunzmann** [comment]
Can you merge this?

**Comment by artemrizhov** [comment]
Hm.. I've merged it, but that was not 1.x, but 1.1 wich is detached again.

**Comment by artemrizhov** [comment]
We probably need to hard reset 1.1 to v1.x and then merge add-deploy-to-1.1 again.

**Comment by niccokunzmann** [comment]
1.1 and 1.x have been the same.

Are these the next steps from your perspective?

- delete 1.x
- delete 2.x
- merge 1.1 into master

**Comment by artemrizhov** [comment]
It looks like the 1.1 branch was behind the v1.x branch. Please see the [graph](https://github.com/niccokunzmann/hanging_threads/network). This is my fault, I have had to check this before accepting PR :)

**Comment by niccokunzmann** [comment]
Can we just merge #64? This would update it from my perspective.

**Comment by artemrizhov** [comment]
Yes, we can if you are ok with such complicated history :)

**Comment by niccokunzmann** [comment]
Yes. It will be forgotten soon.

**Comment by artemrizhov** [comment]
Oh no. We've merged master into 1.1 somehow :-\ I'm always confused with "base" and "compare" when creating new PR. It should be named "from" and "to".

**Comment by artemrizhov** [comment]
@niccokunzmann Could you please hard reset 1.1 to db340d4960c2541e660da22ae1d11b5649870f22 ?

**Comment by artemrizhov** [comment]
Btw, this merge have not produced new version on [pypi](https://pypi.python.org/pypi/hanging_threads). I thought it should be created automatically now.

**Comment by niccokunzmann** [comment]
yes, I also think that. Let's merge eachother's pull-requests and never merge own pull-requests.

**Comment by niccokunzmann** [comment]
I will revert your merge, ok?

**Comment by niccokunzmann** [comment]
I found the mistake: the branches should be named "v1.1" and "v2.0". I will change this, now.
I also created the branch "v1.1".

**Comment by artemrizhov** [comment]
> Let's merge eachother's pull-requests and never merge own pull-requests.

Hm, I beleave I did not merge my PR this time. I just created it, but now I even can't find it for some reason. It's gone.

**Comment by niccokunzmann** [comment]
^^ I know the mistake!

**Comment by niccokunzmann** [comment]
It was mine: I merged master into this branch.

**Comment by niccokunzmann** [comment]
I will see if I can create a PR that works without merging master into v1.1.
Sorry for the assumption you had something to do with it.

**Comment by artemrizhov** [comment]
Ooops! You did this again! You merged master into v1.1

**Comment by artemrizhov** [comment]
And now you have 1.1.1 with features from 2.x :)

**Comment by niccokunzmann** [comment]
-.- yes . I will try again ! :)

**Comment by artemrizhov** [comment]
> Let's merge eachother's pull-requests and never merge own pull-requests.

:-D

**Comment by artemrizhov** [comment]
Don't forget to remove wrong versions from https://pypi.python.org/pypi/hanging_threads

**Comment by niccokunzmann** [comment]
Did it.

**Comment by niccokunzmann** [comment]
![image](https://cloud.githubusercontent.com/assets/564768/22222801/8d725f00-e1b8-11e6-9e70-8f87dcd8d714.png)

**Comment by artemrizhov** [comment]
Do you think 1.1.0 is also wrong?

**Comment by niccokunzmann** [comment]
It probably is not.

**Comment by niccokunzmann** [comment]
This time, it should probably work.

**Comment by niccokunzmann** [comment]
I also protected the deploy branches:

![image](https://cloud.githubusercontent.com/assets/564768/22222913/24c68b10-e1b9-11e6-948e-b2e8c51192a1.png)

**Comment by artemrizhov** [comment]
Ok, the merges and diffs look fine now.

**Comment by artemrizhov** [comment]
The last thing is to implement a script that will compile and publish [release notes](https://github.com/niccokunzmann/hanging_threads/releases) :)

**Comment by niccokunzmann** [comment]
Thanks for your support! I am closing this and will create issues from what I learned.
