### ISSUE TITLE
remove "v" from __version__

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/hanging_threads#69]
See [here](https://github.com/niccokunzmann/hanging_threads/blob/v1.1.0/hanging_threads.py#L32):

The `__version__` variable has a "v" in the beginning. All works fine. setup.py is also fine.
Is this a problem in any case? Should the "v" be removed?

**Comment by artemrizhov** [comment]
[PEP 0396](https://www.python.org/dev/peps/pep-0396/):

> Module version numbers SHOULD conform to the normalized version format specified in PEP 386 [6] .

[PEP 0386](https://www.python.org/dev/peps/pep-0386/):

> he pseudo-format supported is:
> N.N[.N]+[{a|b|c|rc}N[.N]+][.postN][.devN]

**Comment by niccokunzmann** [comment]
This is the line to change: https://github.com/niccokunzmann/hanging_threads/blob/v2.0.1/create-tag-on-deploy-branch.sh#L67

**Comment by niccokunzmann** [comment]
I will work on it, so we can deploy happily ever after.

**Comment by artemrizhov** [comment]
@niccokunzmann Why does Trevis commit version into git? Is this really needed to build the package?

**Comment by niccokunzmann** [comment]
My idea was that the tag represents the exact source code of the package uploaded to pypi. You can create an issue to discuss this.

**Comment by artemrizhov** [comment]
Nice idea!
