### ISSUE TITLE
Improve test_interval documentation

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/hanging_threads#80]
In #76, we can see that the wording for the documentation concerning the test_interval parameter can be changed to be more understandable.

**Comment by MarkoMackic** [comment]
I don't know how to form it concisely, maybe
`Checks are done in intervals of 100 ms` <- using word interval will be self explanatory in terms of parameter name

**Comment by MarkoMackic** [comment]
I issued a  pull request for v2.0, this can now be closed  ?

**Comment by niccokunzmann** [comment]
@artemrizhov Would you close this?

**Comment by artemrizhov** [comment]
I feel like there are too many phrases about the interval:
1. This mean the check will happen 10 times per second.
2. This happens again every 10 seconds
3. Checks are done in intervals of 100ms.

**Comment by MarkoMackic** [comment]
I don't know, whatever you agree on, I'll correct.

**Comment by niccokunzmann** [comment]
I am grateful for that @MarkoMackic wants to help.
I am also grateful that @artemrizhov wants to help.

What I observe is:
- We have been working on this issue for [three days](https://github.com/niccokunzmann/hanging_threads/pull/76#pullrequestreview-18939289).
- Other changes do not ship.
![image](https://cloud.githubusercontent.com/assets/564768/22443349/e711bd7c-e73e-11e6-978c-538a7bae9c43.png)

I am unsure of what changes @artemrizhov requests.
In order for me to get clarity of what this issue is about, @artemrizhov would you be willing to create a pull-request or list requirements for the readme?

What I hope to have is a satisfactory, fun and fulfilling experience for all who contribute to the project.
- Is it true that @artemrizhov  would like @MarkoMackic  to do the changes?
- What are both your motivations to do so?
- How can we close this issue and move on to other problems?

I would like to hear both your thoughts on this, if you like.

**Comment by artemrizhov** [comment]
> We have been working on this issue for three days.

It probably was open for three days, but I beliave nobody was working on it all those days. I think this is important to distiguish "open" and "in work".

> Is it true that @artemrizhov would like @MarkoMackic to do the changes?

This is almost true. I just proposed to change the text because I don't like the final version.

> What are both your motivations to do so?

I don't feel any motivation since the changes are merged already. Obsolete documentation was really motivating. But now it is fixed and merged, so this is probably a variant for years. I think this is a downside of the optimistic merging that you was talking about in #77.

> How can we close this issue and move on to other problems?

Just press the "Close" button ;)

**Comment by artemrizhov** [comment]
It seems that changes are stuck and nobody want to say the final words. I think this issue should be closed as is, because there is no any sense to keep this ticket open. If you think it should not then please reopen.
